[2020-02-04 14:54:39 +0000] [16268] [INFO] Starting gunicorn 19.7.1
[2020-02-04 14:54:39 +0000] [16268] [INFO] Listening at: http://0.0.0.0:8000 (16268)
[2020-02-04 14:54:39 +0000] [16268] [INFO] Using worker: sync
[2020-02-04 14:54:39 +0000] [16271] [INFO] Booting worker with pid: 16271
[2020-02-04 14:54:39 +0000] [16271] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 377, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'evalmgr'
[2020-02-04 14:54:39 +0000] [16271] [INFO] Worker exiting (pid: 16271)
[2020-02-04 14:54:39 +0000] [16268] [INFO] Shutting down: Master
[2020-02-04 14:54:39 +0000] [16268] [INFO] Reason: Worker failed to boot.
[2020-02-04 14:56:00 +0000] [16298] [INFO] Starting gunicorn 19.7.1
[2020-02-04 14:56:00 +0000] [16298] [INFO] Listening at: http://0.0.0.0:8000 (16298)
[2020-02-04 14:56:00 +0000] [16298] [INFO] Using worker: sync
[2020-02-04 14:56:00 +0000] [16301] [INFO] Booting worker with pid: 16301
[2020-02-04 14:56:00 +0000] [16301] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 377, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'evalmgr'
[2020-02-04 14:56:00 +0000] [16301] [INFO] Worker exiting (pid: 16301)
[2020-02-04 14:56:00 +0000] [16298] [INFO] Shutting down: Master
[2020-02-04 14:56:00 +0000] [16298] [INFO] Reason: Worker failed to boot.
